In [10]:
import pandas as pd
import numpy as np

In [3]:
#Experiment 1
elasticstime = pd.read_csv('elasticsearch-instrument-stime.txt')
elasticnostime = pd.read_csv('elasticsearch-noinstrument-stime.txt')
bigSTIME = pd.read_csv('experiment-big-stime-allkw.txt')
inst = pd.read_csv('elastic-instrumented.txt')
noinst = pd.read_csv('elastic-normal.txt')

#energy1a = pd.read_csv('experiment1a-energy.txt')
#stime1a = pd.read_csv('experiment1a-stime.txt')
#entryexit1a = pd.read_csv('experiment1a.txt', sep=';', names=['ThreadID', 'FuncID', 'Timestamp'])

In [4]:
entryexit2b['dif'] = entryexit2b.groupby('FuncID')['Timestamp'].diff(-1) * (-1)

In [5]:
a = entryexit2b.dropna(axis=0, how='any')
a['dif'].mean()

3158.9868370112272

In [6]:
df3 = a[~(a['dif'] >= 5000)]

In [7]:
df3['dif'].mean()

1142.3363141524105

In [17]:
energy2b['a57_power'].mean()

0.10884461222187403

In [20]:
noinst['kw_lengh'].mean()

12.861972394478896

In [5]:
import matplotlib.pyplot as plt

x = np.arange(1404)
y = np.array(stime1c['took_ms'])
y = y[200:1604]
z = np.array(stime1b['took_ms'])
z = z[200:1604]
y = np.array(stime1c['took_ms'])
y = y[200:1604]
z = np.array(stime1b['took_ms'])
z = z[200:1604]
k = np.array(stime2b['took_ms'])
k = z[0:1604]
plt.plot(x, y, 'r', label='Function-based Scheduling')
plt.plot(x, z, 'b', label='Only big-cores')
plt.plot(x, k, 'g', label='Only small-cores')
plt.xlabel('Samples')
plt.ylabel('Service Time')


plt.show()

In [17]:
import numpy

for q in [50, 90, 95, 100]:
  print ("{}%% percentile: {}".format (q, np.percentile(inst['took_ms'], q)))

50%% percentile: 596.0
90%% percentile: 993.2
95%% percentile: 1130.0
100%% percentile: 1932.0

In [18]:
import numpy

for q in [50, 90, 95, 100]:
  print ("{}%% percentile: {}".format (q, np.percentile(noinst['took_ms'], q)))

50%% percentile: 615.0
90%% percentile: 1028.2
95%% percentile: 1160.0
100%% percentile: 2321.0

In [10]:
y = 0:10

SyntaxError: invalid syntax (<ipython-input-10-8ec5985727f4>, line 1)

In [8]:
len(y)

1604

In [4]:
len(k)

1204

In [12]:
bigStime = pd.read_csv('experiment-big-stime-allkw.txt')
bigEnergy = pd.read_csv('experiment-big-energy-allkw.txt')
bigInOut = pd.read_csv('experiment-big-allkw-inout.txt', sep=';', names=['ThreadID', 'FuncID', 'mslong'])

lilStime = pd.read_csv('experiment-little-stime-allkw.txt')
lilEnergy = pd.read_csv('experiment-little-energy-allkw.txt')
lilInOut = pd.read_csv('experiment-little-allkw-inout.txt', sep=';', names=['ThreadID', 'FuncID', 'mslong'])

In [23]:
#bigInOut['dif'] = bigInOut.groupby('FuncID')['Timestamp'].diff(-1) * (-1)
#_bigInOut = bigInOut.dropna(axis=0, how='any')

In [32]:
#df = bigInOut[~bigInOut['Timestamp'].isin(bigEnergy['mslong'])].dropna()

In [13]:
# Juntar InOut com Energy
_bigInOut = bigInOut.merge(bigEnergy, on=['mslong'])
_lilInOut = lilInOut.merge(bigEnergy, on=['mslong'])

In [14]:
_bigInOut['dif'] = _bigInOut.groupby('FuncID')['a57_power'].diff(-1) * (-1)
_lilInOut['dif'] = _lilInOut.groupby('FuncID')['a53_power'].diff(-1) * (-1)

In [16]:
KAKA = _bigInOut.dropna()
KAKA = KAKA.reset_index()
KEKE = _lilInOut.dropna()
#KEKE = KEKE.reset_index()
KEKE

Empty DataFrame
Columns: [ThreadID, FuncID, mslong, sys_current, a57_current, a53_current, gpu_current, sys_voltage, a57_voltage, a53_voltage, gpu_voltage, sys_power, a57_power, a53_power, gpu_power, sys_energy, a57_energy, a53_energy, gpu_energy, dif]
Index: []

In [3]:
import numpy as np
from pylab import *
import pandas as pd
import matplotlib.pyplot as plt

bigSTIME = pd.read_csv('elastic-instrumented.txt')
smallSTIME = pd.read_csv('elastic-normal.txt')

# Create some test data
dx = .01
X  = np.arange(0,4999,20)
Y  = bigSTIME['took_ms']

# Normalize the data to a proper PDF
Y /= (dx*Y).sum()

# Compute the CDF
CY = np.cumsum(Y*dx)

# Plot both
#plot(X,Y)
plot(X,CY,'r--')

show()

ValueError: x and y must have same first dimension

In [7]:
bigSTIME

       timestamp  kw_lengh  took_ms
0     1523133063         3      890
1     1523133064        11      734
2     1523133064         1      387
3     1523133064         2       67
4     1523133065        16      702
5     1523133065         4      113
6     1523133065         4      146
7     1523133066        12      504
8     1523133066         2       90
9     1523133066         4       83
10    1523133066         3      137
11    1523133066         3      165
12    1523133067        11      353
13    1523133067         3       43
14    1523133067         3      167
15    1523133067         1      108
16    1523133067         2      240
17    1523133067         2       52
18    1523133067         2       42
19    1523133068         3      164
20    1523133068         7      178
21    1523133068         3       89
22    1523133068         3       28
23    1523133068         3       97
24    1523133068         1       19
25    1523133068         1       34
26    1523133068         3       32
27    1523133068         2       97
28    1523133068         1       21
29    1523133069        17      381
...          ...       ...      ...
4969  1523133484         3       35
4970  1523133484        13      200
4971  1523133485        11      126
4972  1523133485         2       38
4973  1523133485         2      153
4974  1523133485         1       52
4975  1523133485         4      174
4976  1523133485         2       83
4977  1523133485         1        5
4978  1523133485         3       18
4979  1523133485         3       55
4980  1523133485         3       92
4981  1523133485         2       11
4982  1523133485         5       24
4983  1523133485         7      146
4984  1523133485         1        9
4985  1523133485         1        5
4986  1523133486         5       21
4987  1523133486         1        7
4988  1523133486         4      105
4989  1523133486         1        7
4990  1523133486         4       69
4991  1523133486         3      135
4992  1523133486         2      143
4993  1523133486         2       20
4994  1523133486         3       37
4995  1523133486         1       57
4996  1523133486         4       85
4997  1523133486         1       74
4998  1523133486         1        7

[4999 rows x 3 columns]

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

bigSTIME = pd.read_csv('elasticsearch-instrument-stime.txt')
smallSTIME = pd.read_csv('elasticsearch-noinstrument-stime.txt')

N = 9999
Z = bigSTIME['took_ms']
# method 1
H,X1 = np.histogram( Z, bins = 10, normed = True )
#dx = X1[1] - X1[0]
#F1 = np.cumsum(H)*dx
#method 2
X2 = np.sort(Z)
F2 = np.array(range(N))/float(N)
plt.plot(X2, F2, label='Instrumented (3 KW)')

Z = smallSTIME['took_ms']
# method 1
H,X1 = np.histogram( Z, bins = 10, normed = True )
#dx = X1[1] - X1[0]
#F1 = np.cumsum(H)*dx
#method 2
X2 = np.sort(Z)
F2 = np.array(range(N))/float(N)
plt.plot(X2, F2, label='Normal (3 KW)')




#plt.plot(X1[1:], F1, label='Big Core')
#plt.plot(X2, F2, label='Big (Normal)')
legend = plt.legend(loc='upper right')
plt.xlabel('Service Time')
plt.ylabel('Probability')
plt.title('Cumulative Distributive Funcion')
#plt.plot(X2, F2, label='Big Core')
plt.show()

ValueError: x and y must have same first dimension

In [5]:
smallSTIME

       timestamp  kw_lengh  took_ms
0     1522688598         3     1403
1     1522688598         2      156
2     1522688598         3      123
3     1522688599         6     1043
4     1522688599         1      480
5     1522688600         4      335
6     1522688600         2      379
7     1522688601        11      897
8     1522688602         3      348
9     1522688602         3      126
10    1522688602         4      181
11    1522688602         3      349
12    1522688602         4       92
13    1522688602         2       55
14    1522688603         4      191
15    1522688603         3      135
16    1522688603         2      361
17    1522688604         3      415
18    1522688604         3       75
19    1522688604         1       73
20    1522688604         1       86
21    1522688604         4      194
22    1522688604         4      198
23    1522688605         1      283
24    1522688605         4       97
25    1522688605         3      387
26    1522688606        11      536
27    1522688606         1       65
28    1522688606         2      241
29    1522688606         7      377
...          ...       ...      ...
9969  1522690534         4       96
9970  1522690534         5      372
9971  1522690534         5       61
9972  1522690534         1       25
9973  1522690535         3       97
9974  1522690535         7      442
9975  1522690536        15      613
9976  1522690536         4      209
9977  1522690536         1       15
9978  1522690536         1       39
9979  1522690536         7      174
9980  1522690536         1       25
9981  1522690536         2      251
9982  1522690536         1       20
9983  1522690537         4      204
9984  1522690537         4      186
9985  1522690537         2       35
9986  1522690537         3       43
9987  1522690538        15      981
9988  1522690538         7      145
9989  1522690538         4      104
9990  1522690539         3      458
9991  1522690539         3      524
9992  1522690540         7      477
9993  1522690540         1       18
9994  1522690540         5       77
9995  1522690540         4       98
9996  1522690540         2      259
9997  1522690541         2      269
9998  1522690541         4      106

[9999 rows x 3 columns]

In [1]:
import numpy as np
import scipy.stats

# generate data samples
data = scipy.stats.expon.rvs(loc=0, scale=1, size=1000, random_state=123)
scipy.stats.gaussian_kde(data)
# test values for the bw_method option ('None' is the default value)
bw_values =  [None, 0.1, 0.01]

# generate a list of kde estimators for each bw
kde = [scipy.stats.gaussian_kde(data) for bw in bw_values]


# plot (normalized) histogram of the data
import matplotlib.pyplot as plt 
plt.hist(data, 50, normed=1, facecolor='green', alpha=0.5);

# plot density estimates
t_range = np.linspace(-2,8,200)
for i, bw in enumerate(bw_values):
    plt.plot(t_range,kde[i](t_range),lw=2, label='bw = '+str(bw))
plt.xlim(-1,6)
plt.legend(loc='best')

In [ ]:
import numpy as np
import pandas as pd
from scipy.interpolate import UnivariateSpline
from matplotlib import pyplot as plt

bigTime = pd.read_csv('elasticsearch-instrument-stime.txt')
smallTime = pd.read_csv('elastic-instrumented.txt')

N = 4999
n = N//10
s = bigTime['took_ms']   # generate your data sample with N elements
p, x = np.histogram(s, bins=n) # bin it into n = N//10 bins
x = x[:-1] + (x[1] - x[0])/2   # convert bin edges to centers
f = UnivariateSpline(x, p, s=n)
plt.plot(x, f(x), label='3 KW')

s = smallTime['took_ms']   # generate your data sample with N elements
p, x = np.histogram(s, bins=n) # bin it into n = N//10 bins
x = x[:-1] + (x[1] - x[0])/2   # convert bin edges to centers
f = UnivariateSpline(x, p, s=n)
plt.plot(x, f(x), label='12 KW')

legend = plt.legend(loc='upper right')
plt.xlabel('Service Time')
plt.ylabel('Number of Times')
plt.title('Probability density funcion')
plt.show()

In [4]:
smallTime

       timestamp  kw_lengh  took_ms
0     1523032064        12      409
1     1523032064        11      681
2     1523032065        16      730
3     1523032065        16      363
4     1523032066        14      291
5     1523032066        14      244
6     1523032067        13      715
7     1523032067        14      349
8     1523032068        15      759
9     1523032069        13     1132
10    1523032070        17      738
11    1523032070         7      454
12    1523032071        17      381
13    1523032071         7      224
14    1523032072        16      647
15    1523032072        11      600
16    1523032073        12      451
17    1523032073        14      293
18    1523032073        11      251
19    1523032074        16     1168
20    1523032075        14      442
21    1523032076        17     1156
22    1523032076        11      161
23    1523032077        13      589
24    1523032077        13      534
25    1523032078        11      832
26    1523032079        13      577
27    1523032080        16     1268
28    1523032081        13      501
29    1523032081        13      229
...          ...       ...      ...
4969  1523032046         7      205
4970  1523032047        11      209
4971  1523032047        17      688
4972  1523032048        14      670
4973  1523032049        16      743
4974  1523032049        16      492
4975  1523032050        12      743
4976  1523032051        11      421
4977  1523032051        16      501
4978  1523032052        17      863
4979  1523032053        13      902
4980  1523032054        15      669
4981  1523032054        13      643
4982  1523032055        12      421
4983  1523032055        14      417
4984  1523032056        17      642
4985  1523032056         7      593
4986  1523032057         7      135
4987  1523032057        15      543
4988  1523032058        15      827
4989  1523032058        12      453
4990  1523032059         7      624
4991  1523032060        12      755
4992  1523032060         7      210
4993  1523032061        13      368
4994  1523032061        14      502
4995  1523032062         7      635
4996  1523032063        17      921
4997  1523032063         7      111
4998  1523032063         7      304

[4999 rows x 3 columns]

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

bigSTIME = pd.read_csv('experiment-big-stime-allkw.txt')
smallSTIME = pd.read_csv('experiment-little-stime-allkw.txt')

N = 4999
Z = bigSTIME['took_ms']
# method 1
H,X1 = np.histogram( Z, bins = 10, normed = True )
#dx = X1[1] - X1[0]
#F1 = np.cumsum(H)*dx
#method 2
X2 = np.sort(Z)
F2 = np.array(range(N))/float(N)
plt.plot(X2, F2, label='Big')

Z = smallSTIME['took_ms']
# method 1
H,X1 = np.histogram( Z, bins = 10, normed = True )
#dx = X1[1] - X1[0]
#F1 = np.cumsum(H)*dx
#method 2
X2 = np.sort(Z)
F2 = np.array(range(N))/float(N)
plt.plot(X2, F2, label='Small')




#plt.plot(X1[1:], F1, label='Big Core')
#plt.plot(X2, F2, label='Big (Normal)')
legend = plt.legend(loc='upper right')
plt.xlabel('Service Time')
plt.ylabel('Probability')
plt.title('Cumulative Distributive Funcion')
#plt.plot(X2, F2, label='Big Core')
plt.show()

In [2]:
bigSTIME

       timestamp  kw_lengh  took_ms
0     1523133063         3      890
1     1523133064        11      734
2     1523133064         1      387
3     1523133064         2       67
4     1523133065        16      702
5     1523133065         4      113
6     1523133065         4      146
7     1523133066        12      504
8     1523133066         2       90
9     1523133066         4       83
10    1523133066         3      137
11    1523133066         3      165
12    1523133067        11      353
13    1523133067         3       43
14    1523133067         3      167
15    1523133067         1      108
16    1523133067         2      240
17    1523133067         2       52
18    1523133067         2       42
19    1523133068         3      164
20    1523133068         7      178
21    1523133068         3       89
22    1523133068         3       28
23    1523133068         3       97
24    1523133068         1       19
25    1523133068         1       34
26    1523133068         3       32
27    1523133068         2       97
28    1523133068         1       21
29    1523133069        17      381
...          ...       ...      ...
4969  1523133484         3       35
4970  1523133484        13      200
4971  1523133485        11      126
4972  1523133485         2       38
4973  1523133485         2      153
4974  1523133485         1       52
4975  1523133485         4      174
4976  1523133485         2       83
4977  1523133485         1        5
4978  1523133485         3       18
4979  1523133485         3       55
4980  1523133485         3       92
4981  1523133485         2       11
4982  1523133485         5       24
4983  1523133485         7      146
4984  1523133485         1        9
4985  1523133485         1        5
4986  1523133486         5       21
4987  1523133486         1        7
4988  1523133486         4      105
4989  1523133486         1        7
4990  1523133486         4       69
4991  1523133486         3      135
4992  1523133486         2      143
4993  1523133486         2       20
4994  1523133486         3       37
4995  1523133486         1       57
4996  1523133486         4       85
4997  1523133486         1       74
4998  1523133486         1        7

[4999 rows x 3 columns]

In [2]:
import numpy as np
import pandas as pd
from scipy.interpolate import UnivariateSpline
from matplotlib import pyplot as plt

bigTime = pd.read_csv('experiment-big-stime-allkw.txt')
smallTime = pd.read_csv('experiment-little-stime-allkw.txt')


N = 4999
n = N//10
s = bigTime['took_ms']   # generate your data sample with N elements
p, x = np.histogram(s, bins=n) # bin it into n = N//10 bins
x = x[:-1] + (x[1] - x[0])/2   # convert bin edges to centers
f = UnivariateSpline(x, p, s=n)
plt.plot(x, f(x), label='Big')

s = smallTime['took_ms']   # generate your data sample with N elements
p, x = np.histogram(s, bins=n) # bin it into n = N//10 bins
x = x[:-1] + (x[1] - x[0])/2   # convert bin edges to centers
f = UnivariateSpline(x, p, s=n)
plt.plot(x, f(x), label='Small')

legend = plt.legend(loc='upper right')
plt.xlabel('Service Time')
plt.ylabel('Number of Times')
plt.title('Probability density funcion')
plt.show()

In [6]:
n

499

In [11]:
from scipy.stats import norm
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


fig, ax = plt.subplots(1, 1)

mean, var, skew, kurt = norm.stats(moments='mvsk')
x = bigTime['took_ms']
#ax.plot(x, norm.ppf(x),'r-', lw=5, alpha=0.6, label='norm pdf')
rv = norm()
ax.plot(x, rv.ppf(x), 'k-', lw=2, label='frozen pdf')

#vals = norm.ppf([0.001, 0.5, 0.999])
#np.allclose([0.001, 0.5, 0.999], norm.cdf(vals))

#r = norm.rvs(size=1000)
ax.hist(r, normed=True, histtype='stepfilled', alpha=0.2)
ax.legend(loc='best', frameon=False)
plt.show()

In [10]:
rv

In [16]:
from scipy import stats
import scipy as sp
def norm_sf(mean=0.0, std=1.0):
    # 50 numbers between -3σ and 3σ
    x = sp.linspace(-3*std, 3*std, 50)
    # SF at these values
    y = stats.norm.sf(x, loc=mean, scale=std)

    plt.plot(x,y, color="black")
    plt.xlabel("Variate")
    plt.ylabel("Probability")
    plt.title("SF for Gaussian of mean = {0} & std. deviation = {1}".format(
               mean, std))
    plt.draw()

In [17]:
stats.norm.sf(0.0, loc=0.0, scale=1.0)

0.5

In [25]:
# There are n+1 possible number of "successes": 0 to n.
x = range(n+1)
y = stats.binom.pmf(x, n, p)
plt.plot(x,y,"o", color="black")

    # Format x-axis and y-axis.
plt.axis([-(max(x)-min(x))*0.05, max(x)*1.05, -0.01, max(y)*1.10])
plt.xticks(x)
plt.title("Binomial distribution PMF for tries = {0} & p ={1}".format(n,p))
plt.xlabel("Variate")
plt.ylabel("Probability")

plt.draw()

ValueError: operands could not be broadcast together with shapes (499,) (500,)

In [20]:
import numpy as np
import scipy.stats as ss
import matplotlib.pyplot as plt

a = bigTime['took_ms']
plt.hist(a, normed=True)

xs = np.linspace(0, 2000, 5)
plt.plot(xs, ss.norm.pdf(xs, 78, 74), label='pdf')
#plt.plot(xs, ss.norm.cdf(xs, 4, 2), label='cdf')
plt.show()

In [15]:
bigTime['took_ms'].skew()

1.9949978007042146

In [24]:
from scipy.stats import norm
mean, var, skew, kurt = bigTime['took_ms'].mean(), bigTime['took_ms'].var(), bigTime['took_ms'].skew(), bigTime['took_ms'].kurt()
x = bigTime['took_ms']
plt.plot(x, norm.pdf(x), 'r-', lw=5, alpha=0.6, label='norm pdf')
plt.show()

78.574714942988592

In [35]:
import pandas as pd
import numpy as np

big200 = pd.read_csv('200k-experiment-big.txt')

In [32]:
took_ms = np.array(big200['took_ms'].values.tolist())
big200['took_ms'] = np.where(took_ms > 3000, 3000, took_ms).tolist()

In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

N = 199999
Z = big200['took_ms']
# method 1
H,X1 = np.histogram( Z, bins = 10, normed = True )
#dx = X1[1] - X1[0]
#F1 = np.cumsum(H)*dx
#method 2
X2 = np.sort(Z)
F2 = np.array(range(N))/float(N)
plt.plot(X2, F2, label='Big')

legend = plt.legend(loc='upper right')
plt.xlabel('Service Time')
plt.ylabel('Probability')
plt.title('Cumulative Distributive Funcion')
plt.show()

In [16]:
import numpy as np 
import matplotlib as mpl

mpl.use('agg')
import matplotlib.pyplot as plt

a = np.array(big200['took_ms'].values.tolist())
b = np.array(big200['kw_lengh'].values.tolist())

data_to_plot = [a, b]

In [18]:
# Create a figure instance
fig = plt.figure(1, figsize=(9, 6))

# Create an axes instance
ax = fig.add_subplot(111)

# Create the boxplot
bp = ax.boxplot(data_to_plot)

# Save the figure
fig.savefig('fig1.png', bbox_inches='tight')

In [50]:
big200 = pd.read_csv('200k-experiment-big.txt')
big200 = big200[big200.kw_lengh == 1]

In [51]:
big200

         timestamp  kw_lengh  took_ms
5       1523551002         1      263
8       1523551005         1      504
9       1523551006         1      782
13      1523551011         1      431
16      1523551014         1      152
33      1523551028         1      354
66      1523551055         1      378
68      1523551055         1      309
69      1523551056         1      326
72      1523551056         1      117
91      1523551067         1       45
92      1523551067         1       31
94      1523551068         1      164
97      1523551069         1      182
98      1523551069         1      271
99      1523551069         1       20
108     1523551073         1       21
116     1523551077         1       64
145     1523551088         1      163
148     1523551089         1      238
155     1523551091         1      225
161     1523551092         1       29
166     1523551094         1       93
168     1523551094         1      116
170     1523551094         1      126
173     1523551095         1      155
177     1523551096         1       87
179     1523551097         1      300
184     1523551098         1      206
186     1523551098         1       84
...            ...       ...      ...
199892  1523563710         1       59
199898  1523563711         1       75
199899  1523563711         1        6
199902  1523563711         1       86
199905  1523563711         1        7
199906  1523563711         1       69
199908  1523563711         1        4
199915  1523563712         1        8
199916  1523563712         1       82
199918  1523563712         1        6
199920  1523563712         1        6
199921  1523563712         1       32
199924  1523563713         1        7
199925  1523563713         1        7
199941  1523563714         1        8
199943  1523563714         1        8
199946  1523563714         1        6
199947  1523563714         1        7
199949  1523563714         1        6
199965  1523563715         1       15
199967  1523563715         1        7
199968  1523563715         1        6
199971  1523563715         1       14
199972  1523563715         1       58
199978  1523563716         1       13
199982  1523563716         1       13
199984  1523563716         1        6
199993  1523563717         1       10
199996  1523563717         1        7
199998  1523563717         1        9

[46122 rows x 3 columns]

In [1]:
# libraries
import numpy as np
import matplotlib.pyplot as plt

# width of the bars
barWidth = 0.3

# Choose the height of the blue bars
bars1 = [10, 9, 2]

# Choose the height of the cyan bars
bars2 = [10.8, 9.5, 4.5]

# Choose the height of the error bars (bars1)
yer1 = [0.5, 0.4, 0.5]

# Choose the height of the error bars (bars2)
yer2 = [1, 0.7, 1]

# The x position of bars
r1 = np.arange(len(bars1))
r2 = [x + barWidth for x in r1]

# Create blue bars
plt.bar(r1, bars1, width = barWidth, color = 'blue', edgecolor = 'black', yerr=yer1, capsize=7, label='poacee')

# Create cyan bars
plt.bar(r2, bars2, width = barWidth, color = 'cyan', edgecolor = 'black', yerr=yer2, capsize=7, label='sorgho')

# general layout
plt.xticks([r + barWidth for r in range(len(bars1))], ['cond_A', 'cond_B', 'cond_C'])
plt.ylabel('height')
plt.legend()

# Show graphic
plt.show()

/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/collections.py:548: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == 'face':

In [22]:
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt
import scipy.stats as st
# width of the bars
barWidth = 0.3
bigProb = pd.read_csv('200k-experiment-big.txt') 

took_ms = np.array(bigProb['took_ms'].values.tolist())
bigProb['took_ms'] = np.where(took_ms > 3000, 3000, took_ms).tolist()
kw1 = bigProb[bigProb.kw_lengh == 1]
kw1 = kw1['took_ms'].values
kw2 = bigProb[bigProb.kw_lengh == 2]
kw2 = kw2['took_ms'].values
kw3 = bigProb[bigProb.kw_lengh == 3]
kw3 = kw3['took_ms'].values
kw4 = bigProb[bigProb.kw_lengh == 4]
kw4 = kw4['took_ms'].values
kw5 = bigProb[bigProb.kw_lengh == 5]
kw5 = kw5['took_ms'].values
kw6 = bigProb[bigProb.kw_lengh == 6]
kw6 = kw6['took_ms'].values
kw7 = bigProb[bigProb.kw_lengh == 7]
kw7 = kw7['took_ms'].values
kw8 = bigProb[bigProb.kw_lengh == 8]
kw8 = kw8['took_ms'].values
kw9 = bigProb[bigProb.kw_lengh == 9]
kw9 = kw9['took_ms'].values
kw10 = bigProb[bigProb.kw_lengh == 10]
kw10 = kw10['took_ms'].values
kw11 = bigProb[bigProb.kw_lengh == 11]
kw11 = kw11['took_ms'].values
kw12 = bigProb[bigProb.kw_lengh == 12]
kw12 = kw12['took_ms'].values
kw13 = bigProb[bigProb.kw_lengh == 13]
kw13 = kw13['took_ms'].values
kw14 = bigProb[bigProb.kw_lengh == 14]
kw14 = kw14['took_ms'].values


# Choose the height of the blue bars
bars1 = [kw1.max(), kw2.max(), kw3.max(), kw4.max(), kw5.max(), kw6.max(), kw7.max(), kw11.max(), kw12.max(), kw13.max(), kw14.max()]

a = st.t.interval(0.95, len(kw1)-1, loc=np.mean(kw1), scale=st.sem(kw1))[1]
b = st.t.interval(0.95, len(kw2)-1, loc=np.mean(kw2), scale=st.sem(kw2))[1]
c = st.t.interval(0.95, len(kw3)-1, loc=np.mean(kw3), scale=st.sem(kw3))[1]
d = st.t.interval(0.95, len(kw4)-1, loc=np.mean(kw4), scale=st.sem(kw4))[1]
e = st.t.interval(0.95, len(kw5)-1, loc=np.mean(kw5), scale=st.sem(kw5))[1]
f = st.t.interval(0.95, len(kw6)-1, loc=np.mean(kw6), scale=st.sem(kw6))[1]
g = st.t.interval(0.95, len(kw7)-1, loc=np.mean(kw7), scale=st.sem(kw7))[1]
h = st.t.interval(0.95, len(kw11)-1, loc=np.mean(kw11), scale=st.sem(kw11))[1] 
i = st.t.interval(0.95, len(kw12)-1, loc=np.mean(kw12), scale=st.sem(kw12))[1]
j = st.t.interval(0.95, len(kw13)-1, loc=np.mean(kw13), scale=st.sem(kw13))[1] 
k = st.t.interval(0.95, len(kw14)-1, loc=np.mean(kw14), scale=st.sem(kw14))[1]

# Choose the height of the error bars (bars1)
yer1 = [a, b, c, d, e, f, g, h, i, j, k]
 
# Choose the height of the error bars (bars2) 
# The x position of bars
r1 = np.arange(len(bars1))

# Create blue bars
plt.bar(r1, bars1, width = barWidth, color = 'blue', edgecolor = 'black', yerr=yer1, capsize=7, label='Took Time')
 
# general layout
plt.xticks([r + barWidth for r in range(len(bars1))], ['1', '2', '3', '4', '5', '6', '7', '11', '12', '13', '14'])
plt.ylabel('height')
plt.legend()
 
# Show graphic
plt.show()

In [15]:
import scipy.stats as st
bigProb = pd.read_csv('200k-experiment-big.txt') 

took_ms = np.array(bigProb['took_ms'].values.tolist())
bigProb['took_ms'] = np.where(took_ms > 3000, 3000, took_ms).tolist()
kw1 = bigProb[bigProb.kw_lengh == 1]
kw1 = kw1['took_ms'].values
a = st.t.interval(0.95, len(kw1)-1, loc=np.mean(kw1), scale=st.sem(kw1))[1]

a

17.604757266295575

17.604941322498721